<a href="https://colab.research.google.com/github/tapanauti/Machine-Learning/blob/master/python_for_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Notes from Data Science with python - J Vanderplas**

Because the Python language is so easily readable, you can usually gain another level of insight by reading the source code of the object you’re curious about. IPython pro‐ vides a shortcut to the source code with the double question mark (??):

    In [8]: square??
    Type: function
    String form: <function square at 0x103713cb0> Definition: square(a)
    Source:
    def square(a):
            "Return the square of a"
    return a ** 2

###Tab completion of object contents

To see a list of all available attributes of an object, you can type the name of the object fol‐ lowed by a period (.) character and the Tab key:

     In [10]: L.<TAB>
    L.append   L.copy     L.extend   L.insert   L.remove   L.sort
    L.clear    L.count    L.index    L.pop      L.reverse

###Numpy


Throughout the notes the Numpy will be imported and use as ***np***

    import numpy as np


    x1 = np.random.randint(10, size=6) # One-dimensional array
    x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
    x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

Accessing array rows and columns.

    In[28]: print(x2[:, 0]) # first column of x2 
    [12 7 1]

    In[29]: print(x2[0, :]) # first row of x2
    [12 5 2 4]




Reshaping of Arrays


Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape() method. For example, if you want to put the num‐ bers 1 through 9 in a 3×3 grid, you can do the following:


    In[38]: grid = np.arange(1, 10).reshape((3, 3))
    print(grid)

    [[1 2 3]
     [4 5 6]
     [7 8 9]]


For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

    In[48]: x = np.array([1, 2, 3])
            grid = np.array([[9, 8, 7],
    [6, 5, 4]]) # vertically stack the arrays
    
    np.vstack([x, grid])
    Out[48]: array([[1, 2, 3],
                    [9, 8, 7],
                    [6, 5, 4]])


    In[49]: # horizontally stack the arrays 
            y = np.array([[99],
                          [99]])
            np.hstack([grid, y])
    Out[49]: array([[ 9,  8,  7, 99],
                    [ 6,  5,  4, 99]])

Similarly, np.dstack will stack arrays along the third axis.

Mathematic functions

    In[26]: x = np.arange(1, 6)
    x
    np.add.reduce(x)

    Out[26]: [[1,2,3,4,5]]
             15

             